clinic/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView
from reception.views import ReceptionCreateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', ReceptionCreateView.as_view()),
    url(r'^success/$', TemplateView.as_view(template_name="reception/success.html")),
]

reception/models.py
from django.db import models


class Doctor(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Reception(models.Model):
    date = models.DateField(blank=False)
    hour = models.PositiveSmallIntegerField(
        choices=[(i, i) for i in range(9, 18)]
    )
    doctor = models.ForeignKey(Doctor)
    full_name = models.TextField()

    class Meta:
        unique_together = ("date", "hour", "doctor")

    def __str__(self):
        return str(self.date) + ' : ' + self.doctor.name

reception/views.py
import json
from itertools import groupby

from django.shortcuts import render
from django.views.generic import CreateView
from reception.models import Doctor, Reception


def date_handler(obj):
    if hasattr(obj, 'isoformat'):
        return "{month:02d}/{day:02d}/{year}".format(
            year=obj.year,
            month=obj.month,
            day=obj.day
        )
    return obj


class ReceptionCreateView(CreateView):
    model = Reception
    fields = ['doctor', 'date', 'hour', 'full_name']
    success_url = 'success'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['doctors'] = json.dumps(list(Doctor.objects.all().values()))
        data = {}
        for key, group in groupby(Reception.objects.all().values(), lambda x: x['doctor_id']):
            data[key] = list(group)
        data = json.dumps(data, default=date_handler)
        context['data'] = data
        return context

reception/templates/reception/base.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.1/moment.min.js"></script>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Reception
    </title>
</head>
<body>
<div class="container">
    <div class="row">
        {% block body %}
        {% endblock %}
    </div>
</div>


   
</body>
</html>

reception/templates/reception/reception_form.html
{% extends "reception/base.html" %}
{% load bootstrap3 %}


{% block body %}
<form action="." method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
        {% bootstrap_icon "star" %} Submit
    </button>
    {% endbuttons %}
</form>
<script>
window.django_data = {{data|safe}} ;
window.django_doctors = {{doctors|safe}} ;
$( document ).ready(function() {
  var date = $('#id_date');
  var doctor= $('#id_doctor');
  var hour = $('#id_hour');
  date.datepicker();
  date.datepicker('setDaysOfWeekDisabled', '06');
  var update_hour = function(){
      console.log('start');
      $( "#id_hour option" ).prop( "disabled", false );
      var doctorId = parseInt(doctor.val());
      var dateString = date.val();
      $('#id_hour option').each(function( index ) {
          var option = $( this );
          window.django_data[doctorId].forEach(
                  function(row){
                      console.log(row);
                      if(row['date']==dateString && parseInt(option.val()) == row.hour){
                          option.prop( "disabled", true );
                      }
                  }
                  );


      })
  }
  date.change(update_hour);
  doctor.change(update_hour);





});
</script>
{% endblock %}

reception/templates/reception/success.html
{% block body %}
<h3>Ok</h3>
{% endblock %}